services:
  kafka0:
    image: apache/kafka-native:4.0.0
    container_name: kafka0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka0:9093,2@kafka1:9093,3@kafka2:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTER_BROKER://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092,INTER_BROKER://kafka0:19092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTER_BROKER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTER_BROKER:PLAINTEXT"
    ports:
      - "9092:9092"

  kafka1:
    image: apache/kafka-native:4.0.0
    container_name: kafka1
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka0:9093,2@kafka1:9093,3@kafka2:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTER_BROKER://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9093,INTER_BROKER://kafka1:19092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTER_BROKER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTER_BROKER:PLAINTEXT"
    ports:
      - "9093:9092"

  kafka2:
    image: apache/kafka-native:4.0.0
    container_name: kafka2
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka0:9093,2@kafka1:9093,3@kafka2:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,INTER_BROKER://:19092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9094,INTER_BROKER://kafka2:19092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTER_BROKER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTER_BROKER:PLAINTEXT"
    ports:
      - "9094:9092"

